# Generated by Django 6.0 on 2025-12-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_accesscode_gamevideo_playerprofile_aisummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('manager', 'Manager')], default='player', max_length=10),
        ),
    ]
