# Generated by Django 6.0 on 2025-12-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_accesscode_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
