# Generated by Django 6.0 on 2025-12-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_accesscode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='allowed_email',
            field=models.EmailField(blank=True, help_text='If set, only this email may use the code', max_length=254, null=True),
        ),
    ]
