# Generated by Django 6.0 on 2025-12-23 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_accesscode_created_at_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamevideo',
            options={'ordering': ['-game_date', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='description',
            field=models.TextField(blank=True, help_text='Game summary, notes, or highlights'),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Video duration in seconds'),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='file_size_mb',
            field=models.FloatField(default=0, help_text='File size in MB'),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='game_date',
            field=models.DateField(blank=True, help_text='Date game was played', null=True),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='game_type',
            field=models.CharField(choices=[('full', 'Full Game'), ('highlight', 'Highlights'), ('practice', 'Practice')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on home page'),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='opponent',
            field=models.CharField(blank=True, help_text='Opponent team name', max_length=200),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamevideo',
            name='private',
            field=models.BooleanField(default=True, help_text='Only team members can view'),
        ),
        migrations.AlterField(
            model_name='gamevideo',
            name='title',
            field=models.CharField(help_text="e.g., 'State Championship vs Lincoln High'", max_length=200),
        ),
        migrations.AlterField(
            model_name='gamevideo',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Coach who uploaded', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamevideo',
            name='video',
            field=models.FileField(help_text='MP4, MOV, or MKV (max 2GB)', upload_to='videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='gamevideo',
            index=models.Index(fields=['-game_date'], name='team_gamevi_game_da_376a81_idx'),
        ),
        migrations.AddIndex(
            model_name='gamevideo',
            index=models.Index(fields=['-uploaded_at'], name='team_gamevi_uploade_af897d_idx'),
        ),
    ]
