# Generated by Django 6.0 on 2025-12-25 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis', models.TextField(blank=True, help_text='AI-generated video analysis')),
                ('highlights', models.TextField(blank=True, help_text='Key highlights and moments')),
                ('player_performance', models.TextField(blank=True, help_text='Individual player performance insights')),
                ('tactical_notes', models.TextField(blank=True, help_text='Tactical analysis and suggestions')),
                ('error_message', models.TextField(blank=True, help_text='Error details if analysis failed')),
                ('analysis_model', models.CharField(default='gpt-5.1-codex-max', help_text='GPT model used for analysis', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_analyses_requested', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='team.gamevideo')),
            ],
            options={
                'verbose_name_plural': 'Video Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
