# Generated by Django 6.0 on 2026-01-03 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_videoanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Conversion'), ('processing', 'Converting...'), ('success', 'Converted Successfully'), ('failed', 'Conversion Failed'), ('skipped', 'Skipped (Already MP4)')], default='pending', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('original_format', models.CharField(blank=True, max_length=10)),
                ('original_size_mb', models.FloatField(default=0, help_text='Original file size in MB')),
                ('converted_size_mb', models.FloatField(default=0, help_text='Converted MP4 size in MB (if applicable)')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task UUID', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if conversion failed')),
                ('debug_log', models.TextField(blank=True, help_text='Detailed debug output from ffmpeg and system')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_log', to='team.gamevideo')),
            ],
            options={
                'verbose_name': 'Video Conversion Log',
                'verbose_name_plural': 'Video Conversion Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
