"""
Django settings for volleyball_site project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: keep the secret key used in production secret!
# Read sensitive values from environment in production; fall back to defaults for local dev.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-please-change-this-default",
)

# DEBUG should be False in production. Set DJANGO_DEBUG=True to enable debug.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# ALLOWED_HOSTS can be set as comma-separated values via DJANGO_ALLOWED_HOSTS
ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,*.railway.app").split(",") if h]

# CSRF trusted origins for local development and production
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://localhost',
    'https://eastside-vb-website-production.up.railway.app',
    'https://*.railway.app',
]

# Session and CSRF settings for local development
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # Must be False so JavaScript can read it if needed
CSRF_USE_SESSIONS = False  # Store CSRF token in cookie instead of session
CSRF_COOKIE_AGE = 31449600  # 1 year



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'team',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'volleyball_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'volleyball_site.wsgi.application'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (User-uploaded content like videos)
MEDIA_URL = '/media/'
# Use volume mount on Railway: /data/media
if os.environ.get('RAILWAY_ENVIRONMENT'):
    MEDIA_ROOT = '/data/media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Media file streaming for large videos
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Stream large responses (videos)
STREAMING_CHUNK_SIZE = 8192  # 8KB chunks for smooth video streaming
FILE_UPLOAD_MAX_MEMORY_SIZE = 35 * 1024 * 1024 * 1024  # 35GB

# --- Environment-based overrides and production-ready settings ---
import os as _os

# Read sensitive values from environment (fallbacks kept for local development)
SECRET_KEY = _os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-3xq-23(*y%q*hs#zst(*u4%&v^zw!mf4ut0*s+z#_pdcl)ver#",
)

DEBUG = _os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [h for h in _os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,testserver,*.railway.app,dorris-thalamencephalic-tensibly.ngrok-free.dev").split(",") if h]

# Static files collection target for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Railway.app specific settings
if _os.environ.get('RAILWAY_ENVIRONMENT'):
    # Production settings for Railway
    DEBUG = False
    # Railway handles HTTPS at the edge, so don't redirect
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    ALLOWED_HOSTS = ['*']  # Railway handles routing

# Use WhiteNoise for simple static file serving (if installed)
if 'whitenoise.middleware.WhiteNoiseMiddleware' not in globals().get('MIDDLEWARE', []):
    try:
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    except Exception:
        pass

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

# Celery settings
CELERY_BROKER_URL = _os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')

# OpenAI API settings
OPENAI_API_KEY = _os.environ.get('OPENAI_API_KEY', None)

# GPT model configuration
# Specify which GPT model to use for AI summaries and other OpenAI tasks
# Options: 'gpt-3.5-turbo', 'gpt-4', 'gpt-4-turbo', 'gpt-5.1-codex-max', etc.
OPENAI_GPT_MODEL = _os.environ.get('OPENAI_GPT_MODEL', 'gpt-5.1-codex-max')

# GPT-5.1-Codex-Max configuration
# Enable GPT-5.1-Codex-Max for all clients (set to True for production deployment)
ENABLE_GPT_5_1_CODEX_MAX = _os.environ.get('ENABLE_GPT_5_1_CODEX_MAX', 'False') == 'True'

CELERY_RESULT_BACKEND = _os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Email defaults
DEFAULT_FROM_EMAIL = _os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@localhost')
DEFAULT_FROM_NAME = _os.environ.get('DEFAULT_FROM_NAME', 'Eastside VB')
DEFAULT_REPLY_TO = _os.environ.get('DEFAULT_REPLY_TO', '') or None
